baseURL = "https://georgiyozhegov.github.io/me"
languageCode = "ru"
defaultContentLanguage = "ru"
theme = "PaperMod"
title = "GБлог"

[params]
ShowReadingTime = true
hideSummary = true
disableScrollToTop = true

keywords = [
      "блог",
      "небольшой сайт",
      "мини сайты",
      "личный блог",
      "английский",
      "английский язык",
      "программирование",
]
description = "Мой личный блог о программировании и английском"
author = "Георгий Ожегов"

[params.profileMode]
enabled = true
title = "<title>"
subtitle = "Мой маленький сайт в большом интернете"
imageUrl = "https://i.ibb.co/7YC2KFH/The-Best-Profile-Ever.jpg"
imageWidth = 238
imageHeight = 238

[[params.profileMode.buttons]]
name = "Блог"
url = "/me/blog"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/georgiyozhegov"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/georgiyozhegov"
