baseURL = "https://blog.georgiyozhegov.ru"
languageCode = "ru"
defaultContentLanguage = "ru"
theme = "PaperMod"
title = "GБлог"

[params]
ShowReadingTime = true
ShowCodeCopyButtons = true
showtoc = true
hideSummary = true
disableScrollToTop = true

keywords = [
      "georgiyozhegov",
      "thegblog",
      "gблог",
      "gblog",
      "блог",
      "небольшой сайт",
      "мини сайты",
      "личный блог",
      "авторский блог",
      "английский",
      "английский язык",
      "образовние",
      "программирование",
      "rust",
      "c++",
      "neovim",
      "nvim",
      "vim",
]
description = "Мой личный блог о программировании и английском"
author = "Георгий Ожегов"

[params.assets]
favicon = "/favicon/favicon.ico"
favicon16x16 = "/favicon/favicon-16x16.png"
favicon32x32 = "/favicon/favicon-32x32.png"
apple_touch_icon = "/favicon/apple-icon.png"

[params.profileMode]
enabled = true
title = "<title>"
subtitle = "Мой личный блог о программировании и английском"
imageUrl = "/Logo.png"
imageWidth = 238
imageHeight = 238

[[params.profileMode.buttons]]
name = "Читать"
url = "/read"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/thegblog"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/georgiyozhegov"

[[params.socialIcons]]
name = "Habr"
url = "https://habr.com/ru/users/georgiyozhegov"
