baseURL = "https://georgiyozhegov.github.io/me"
languageCode = "ru"
defaultContentLanguage = "ru"
theme = "PaperMod"
title = "GБлог"

[params]
ShowReadingTime = true
ShowCodeCopyButtons = true
showtoc = true
hideSummary = true
disableScrollToTop = true

keywords = [
      "georgiyozhegov",
      "gблог",
      "gblog",
      "блог",
      "небольшой сайт",
      "мини сайты",
      "личный блог",
      "авторский блог",
      "английский",
      "английский язык",
      "образовние",
      "программирование",
      "rust",
      "c++",
      "neovim",
      "nvim",
      "vim",
]
description = "Мой личный блог о программировании и английском"
author = "Георгий Ожегов"

[params.profileMode]
enabled = true
title = "<title>"
subtitle = "Мой личный блог о программировании и английском"
imageUrl = "/me/Logo.png"
imageWidth = 238
imageHeight = 238

[[params.profileMode.buttons]]
name = "Читать"
url = "/me/blog"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/georgiyozhegov"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/georgiyozhegov"
